### ISSUE TITLE
Localizeddate issue 

### ISSUE THREAD

**Issue by gabva** [vojtasvoboda/oc-twigextensions-plugin#10]
Hi

Thanks for this useful plugin.

When i used {{ post.published_at|localizeddate('medium', 'none', locale) }} i've got : Unknown "localizeddate" filter.

Other filters work well.

Does anyone have an idea ? Am i doing something wrong ?

Thanks a lot

**Comment by gabva** [comment]
Well i'm answering to myself .

I just don't seem to have the php5-intl extension installed on my server ;) 

Hope it well help ;)

**Comment by vojtasvoboda** [comment]
Thanks for your feedback I just updated Readme with php5-intl extension requirement.
