### ISSUE TITLE
Can you add this feature to the plugin pls

### ISSUE THREAD

**Issue by ghost** [vojtasvoboda/oc-twigextensions-plugin#15]
See here: https://github.com/victorhaggqvist/Twig-sort-by-field

Would be nice to have this feature also.

p.s. Thanks for the plugin I use it on all my October CMS websites.

**Comment by vojtasvoboda** [comment]
I have this enhancement in the queue, but if you don't want to wait, please send a pull request. Thanks

**Comment by ghost** [comment]
@vojtasvoboda Thank you, I will wait for you to add this to the plugin. Hopefully it won't take very long to add.

**Comment by vojtasvoboda** [comment]
Version 1.1.3 ready for install at the Market or your backend area.
