### ISSUE TITLE
Uppercase for swedish?

### ISSUE THREAD

**Issue by hambern** [vojtasvoboda/oc-twigextensions-plugin#2]
Hello there... I'm trying to get this working with swedish. When i write:'

'Välkommen' | uppercase

i get:

VäLKOMMEN

This should work:

mb_convert_case($string, MB_CASE_TITLE, "UTF-8");

**Comment by vojtasvoboda** [comment]
Thank you for testing! Problem solved. You can make an update in your application backend.
