### ISSUE TITLE
Multi language trasnlation not work

### ISSUE THREAD

**Issue by ribsousa** [vojtasvoboda/oc-twigextensions-plugin#20]
I'm having a problem with multi language site!

exemple: post published in 12/1/2017 09:25 

Locale set to **en** works fine!
print correct **12 hours ago**

When I change language to **pt-br** not work!
print worong **1 hora atrás**

'timezone' => 'UTC',

**Comment by vojtasvoboda** [comment]
But last time (https://github.com/vojtasvoboda/oc-twigextensions-plugin/issues/8) you fixed it, don't you?

**Comment by bastihilger** [comment]
If I may interrupt - there is something wrong in the pt-br language files. I made the same mistake in the German ones. Only the plural versions have had a placeholder.
I just created a pull request to fix that.

**Comment by vojtasvoboda** [comment]
Thanks @manogi it may be solution. @ribsousa can you please test it on your website?

But it's weird, first section should be for singular version.

**Comment by bastihilger** [comment]
You are right, when I think about it - it should actually just take the plural version.

**Comment by bastihilger** [comment]
I'm sorry, my comment was wrong - the English files also just have the "1" and no placeholder, and that is perfectly fine like that. So the issue must lie somewhere else.

**Comment by vojtasvoboda** [comment]
And when you have sites in **en** and **de** locale, do they have same results? For example when you can see in English "1 hour ago", do you see same in German one?

**Comment by ribsousa** [comment]
I have not tested yet if the problem only occurs with pt-br, I will enable German to verify this

**Comment by ribsousa** [comment]
'timezone' => 'UTC',
In German returned the same result as English

The problem then is in pt-br?

**Comment by ribsousa** [comment]
See! [site](http://iepm.online/pt-br/blog) change language

**Comment by vojtasvoboda** [comment]
Which is the official timezone for PT-BR? Is it same like English and German?

**Comment by ribsousa** [comment]
No, [Time Zone Brazil](https://greenwichmeantime.com/time-zone/south-america/brazil/time-brazil/)

**Comment by vojtasvoboda** [comment]
And when you set CMS timezone to Brazil, it prints correct translation?

**Comment by ribsousa** [comment]
set 'timezone' => 'Brazil/East',
en/de print ok! **22 hours ago**
pt-br print **1 hour ago**

**Comment by bastihilger** [comment]
Maybe we should have a look at the actual lang/pt-br/lang.php file in use here...

**Comment by ribsousa** [comment]
You can check the result [here](http://iepm.online/pt-br/blog)

**Comment by vojtasvoboda** [comment]
@ribsousa You've set timezone to Brazil?

**Comment by ribsousa** [comment]
Yes!

2017-01-13 10:43 GMT-02:00 Vojta Svoboda <notifications@github.com>:

**Comment by vojtasvoboda** [comment]
I don't really know. The translations are taken from https://github.com/KnpLabs/KnpTimeBundle/tree/master/Resources/translations so they should be fine.

This plugin only connect October Translator with Twig Extensions plugin. It doesn't modify the data in any way, so I'm not sure. Maybe the problem is in Twig Extensions.

**Comment by bastihilger** [comment]
It seems it always takes the singular version instead of the plural version. 

The lang file in your repository looks fine. But maybe @ribsousa isn't really using that version? Is that an OctoberCMS installation or something else?

**Comment by ribsousa** [comment]
October clean install!

**Comment by vojtasvoboda** [comment]
Which build? Try to enable `edgeUpdates` at config.

**Comment by bastihilger** [comment]
I just tested this in one of my websites - I have the same problems with pt-br. But now can tweak the files and test better...

**Comment by bastihilger** [comment]
If I replace the complete content of pt-br with the en lang file, I still get the same wrong results

**Comment by bastihilger** [comment]
We are getting closer: if I rename "pt-br" to "pt" and use that, it works correctly.

**Comment by ribsousa** [comment]
**pt** is Portuguese from Portugal

**Comment by bastihilger** [comment]
I know - this is not about that, but about the fact that probably the "-" in the folder name is a problem. I could also have renamed it to "xy".

**Comment by ribsousa** [comment]
ok!

**Comment by bastihilger** [comment]
An underscore also works: renaming the folder to "pt_br" also had good results.
I will prepare a pull request. I guess @vojtasvoboda will merge it and put it on the market place.

Just make sure that after updating the twig extensions plugin you go directly to your language settings in octoberCMS and replace "pt-br" with "pt_br". And the css class of your flag to "flag-icon-pt_br" ;-)

**Comment by vojtasvoboda** [comment]
This is weird, OctoberCMS uses also `pt-br`:
- https://github.com/octobercms/october/tree/master/modules/backend/lang
- https://github.com/octobercms/october/tree/master/modules/cms/lang
- https://github.com/octobercms/october/tree/master/modules/system/lang

With `pt_br` it will not be compatible with OctoberCMS locale settings.

**Comment by bastihilger** [comment]
Ah ok - closed my pull request. But then I'm out of my depth here and you need to take over ;-)

Maybe the knowledge that it works without the dash in the folder name helps a little.

**Comment by bastihilger** [comment]
OK found it - but it is unfortunately a problem with OctoberCMS. It makes use of [this class](https://github.com/symfony/translation/blob/master/PluralizationRules.php) 
But have a look at line 38: it checks if the locale name is longer than 3 characters and then tries to split it at the "_" sign. After that, the locale is basically empty, and the translation falls back to taking the first part of the string in your translation file. So OctoberCMS also should not be using "pt-br" and so on. But it probably never caused problems, because none of these files seem to use the singular/plural version of translation files...

**Comment by vojtasvoboda** [comment]
And can you report this behaviour directly to the October repository and mention this thread? I'm curious about solution :-)

**Comment by ribsousa** [comment]
+1

**Comment by ribsousa** [comment]
Actually renaming the folder to **pt_br** and changing the language setting to **pt_b**r, it works. However octobercms uses **pt-br**; the problem seems to be even the "**-**" as reported by **manogi**.

**Comment by vojtasvoboda** [comment]
I'll wait for @manogi and his Issue to the OctoberCMS repo and we'll see where is the problem.

**Comment by bastihilger** [comment]
Reported it [here](https://github.com/octobercms/october/issues/2611).

**Comment by vojtasvoboda** [comment]
Thanks!
