### ISSUE TITLE
Implementing a 'fileversion' twig filter to prevent browser from caching modified/updated asset files

### ISSUE THREAD

**Issue by jeanniton-mnr** [vojtasvoboda/oc-twigextensions-plugin#25]
Hi!

Can you implement my "fileversion" twig filter to prevent browsers from caching modified/updated asset files?

The workaround I have done to solve this "issue" is addressed there: http://stackoverflow.com/questions/728616/disable-cache-for-some-images

I think this is a common problem.

### Plugin code
```
 public function registerMarkupTags()
    {
       return [
           'filters' => [
                'fileversion' => [$this, 'getFileVersion']
             ],
    }
    public function getFileVersion($filename)
    {
        // Remove http/web address from the file name if there is one
        // to load it locally
        $prefix = url("/");
        $filename_ = trim(preg_replace('/^' . preg_quote($prefix, '/') . '/', '', $filename), '/');

        if (file_exists($filename_))
        {
          $timestamp = filemtime($filename_);
          return $filename . "?" . date ("m.d.y.H.i.s", $timestamp);
        }else
        {
          return $filename . "?";
        }
    }
```

### Usage code sample
`
<img src="{{ 'assets/images/image_file.jpg'|theme|fileversion}}" alt="an image>
`

**Comment by vojtasvoboda** [comment]
Hi, could you please send pull request with tests included? There is automatic checks in GitHub, so your code will be validated.

Thanks a lot
Vojta
