### ISSUE TITLE
Breaks Forgot Password on Backend Login

### ISSUE THREAD

**Issue by leohner** [vojtasvoboda/oc-twigextensions-plugin#33]
When this plugin is installed, you can't use the Forgot Your Password? option when logging into the backend. When typing in the username, the following error message appears: 

![twig-extensions-broken](https://user-images.githubusercontent.com/17093330/30778236-77f82e16-a09e-11e7-8378-9248ba179c42.png)

Thank you!

**Comment by vojtasvoboda** [comment]
I'm going to fix it by #34

**Comment by vojtasvoboda** [comment]
Version 1.2.0 is now ready at the Market. Could you @fuchsli please test it?

Thanks for reporting this issue
Vojta

**Comment by leohner** [comment]
It works great now! Thank you so much for fixing it so quickly!
