### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by tschortsch** [vojtasvoboda/oc-twigextensions-plugin#36]
Since I updated to `v1.2.0` my `composer install` command fails with the following error:
```
The requested package composer/installers ~1.4 exists as composer/installers[v1.3.0] but these are rejected by your constraint.
```

I'm using `Build 419` of OctoberCMS.

**Comment by vojtasvoboda** [comment]
You have to either update October to build 420 (Laravel 5.5) or use version 1.1.3 of this plugin (so just revert plugin in Git).

It's also mentioned in readme: `Tested with the latest stable OctoberCMS build 420 (with Laravel 5.5). For Laravel 5.4 use version 1.1.3.`

October 419 and 420 are not compatible.

**Comment by tschortsch** [comment]
Ah sorry didn't see that, so there is no chance that the `Restore password` issue can be fixed with my current version?

**Comment by vojtasvoboda** [comment]
I've made special branch `laravel54` and copy Restore password fix. Could you please try it? I'm able to do support for old versions and put all fixes also to `laravel54` branch.

**Comment by tschortsch** [comment]
Thanks a lot! Will test it today and give you feedback.

**Comment by tschortsch** [comment]
Tested it and everything works again, thanks!

**Comment by vojtasvoboda** [comment]
Great! I'm glad it works. If you like this plugin, PLEASE make a review: `https://octobercms.com/plugin/vojtasvoboda-twigextensions`

Thanks a lot :-)
