### ISSUE TITLE
Template file issue on update

### ISSUE THREAD

**Issue by Richard-Masefield** [vojtasvoboda/oc-twigextensions-plugin#37]
__string_template__cf7c1832efa2815985d2dab2f78b2eecf36712704253b96a16e92faf8dc4aa57  not found.

**Comment by vojtasvoboda** [comment]
Could you please provide more information? This is after installation? Which October version? Which plugin version? PHP version? Thanks

Have you tried clear cache? `php artisan cache:clear`

**Comment by Richard-Masefield** [comment]
Hi, thanks for the response.
I've tried to clear the cache yes.
Twig Extensions v1.2.0
Running latest version of October.
Had a similar issue once before and had to roll back twig extension plugin to solve.
Error present on Twig::parse() call

**Comment by vojtasvoboda** [comment]
Huh, that's weird. I tried now to install fresh October installation (424) with Twig Extensions plugin (1.2.0) and works well.

Can you put your project somewhere on Git and send me an invitation? I would like to help you, but I don't know where could be a problem.
