### ISSUE TITLE
Get v1.1.0+ to stable?

### ISSUE THREAD

**Issue by Fl0Cri** [vojtasvoboda/oc-twigextensions-plugin#38]
Now that October 420+ is released to stable and current stable build of this plugin doesn't work with it (#29), can you release a working version to stable? (if I remember correctly, it worked well with v1.1.0)

Thanks in advance

**Comment by vojtasvoboda** [comment]
Yes, there is special branch. I've updated Readme of this plugin:

`Tested with the latest stable OctoberCMS build 420 (with Laravel 5.5). For Laravel 5.4 use special branch laravel54.`
