### ISSUE TITLE
Add support for dropdown values

### ISSUE THREAD

**Issue by ghost** [vojtasvoboda/oc-twigextensions-plugin#44]
Hi,

First, thanks to you for providing this plugin. Installed on every october cms project I make and it save my everyday life !

[I created an issue on october CMS github page about the impossibility to display a dropdown value in frontend](https://github.com/octobercms/october/issues/3759). When you print for example {{ model.dropdown }} to the frontend, it will display the dropdown key, not the corresponding value.

The answer of the devs (not agree) is that it's not the job of the core to know what is the value associated to that key for a dropdown. So I need to be done in an external plugin.

Instead of creating a plugin just for that, I wonder if you would accept a PR to officially add this feature into your plugin.

Thank you for your answer.

Best regards,

Alex

**Comment by vojtasvoboda** [comment]
Hi Alex,

yes sure, send a pull-request and I will check it out.

Vojta
