### ISSUE TITLE
Translations sets days months and year with value 1

### ISSUE THREAD

**Issue by joaocosta-azores** [vojtasvoboda/oc-twigextensions-plugin#50]
Hello,

I'm running octobercms build 447.
In English locale it gives me correct time diference eg:.  ```6 months ago``` but in any other language, I get always value 1. An example would be with locale pt-br i get ```1 mês atrás``` instead of ```6 mêses atrás```.

**Comment by vojtasvoboda** [comment]
Hello, please check this issue https://github.com/vojtasvoboda/oc-twigextensions-plugin/issues/42. Is it the same problem you have?
