### ISSUE TITLE
base64_encode/decode (enhancement)

### ISSUE THREAD

**Issue by helmutkaufmann** [vojtasvoboda/oc-twigextensions-plugin#51]
Suggest to add two function, which come handy when creating pages and wanting to send parameters, base63_encode and decode. Code could look like:

```
'base64_encode' => function ($string) { return  base64_encode($string); },
'base64_decode' => function ($string) { return base64_decode($string); },
```

**Comment by vojtasvoboda** [comment]
Feel free to send pull request with tests included and I will merge it as soon as possible.
