### ISSUE TITLE
Having trouble with the Arabic language

### ISSUE THREAD

**Issue by MH-Zarkhani** [vojtasvoboda/oc-twigextensions-plugin#55]
hi 
i add persian(fa) and arabic(ar) to lang directory and use {{ post.published_at | time_diff }} filter but persian  worked and arabic not worked !!!   
Having trouble with the ar

**Comment by vojtasvoboda** [comment]
Hi @MH-Zarkhani, what is the output for arabic? Empty string?

**Comment by MH-Zarkhani** [comment]
this exception :
An exception has been thrown during the rendering of a template ("Unable to choose a translation for "1 یوم قبل|:count یوم قبل" with locale "ar" for value "4". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").").

**Comment by vojtasvoboda** [comment]
@MH-Zarkhani Maybe you have to use `|%count%` instead of `|:count`?

**Comment by MH-Zarkhani** [comment]
this in my code in ar/lang.php
`<?php

return [
    'diff' => [
        'empty' => 'الآن',
        'ago' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ],
        'in' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ]
    ],
];`

**Comment by MH-Zarkhani** [comment]
`<?php

return [
    'diff' => [
        'empty' => 'الآن',
        'ago' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ],
        'in' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ]
    ],
];`

**Comment by MH-Zarkhani** [comment]
ar/lang.php code

<?php

return [
    'diff' => [
        'empty' => 'الآن',
        'ago' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ],
        'in' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ]
    ],
];

**Comment by MH-Zarkhani** [comment]
this code of **_ar/lang.php_** file
```<?php

return [
    'diff' => [
        'empty' => 'الآن',
        'ago' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ],
        'in' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ]
    ],
];```

**Comment by MH-Zarkhani** [comment]
``` <?php

return [
    'diff' => [
        'empty' => 'الآن',
        'ago' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ],
        'in' => [
            'year' => '1 سنة قبل|:count سنة قبل ',
            'month' => '1 شهر قبل|:count شهر قبل',
            'day' => '1 یوم قبل|:count یوم قبل',
            'hour' => '1 ساعة قبل|:count ساعة قبل ',
            'minute' => '1 دقیقة قبل| :count دقیقة قبل ',
            'second' => '1 ثانیة قبل|:count ثانیة قبل',
        ]
    ],
]; ```

**Comment by vojtasvoboda** [comment]
You have to insert `[2, Inf]`, please check Czech translation https://github.com/vojtasvoboda/oc-twigextensions-plugin/blob/master/lang/cs/lang.php

It is working on my computer:
<img width="506" alt="Snímek obrazovky 2019-11-01 v 12 01 37" src="https://user-images.githubusercontent.com/374917/68020680-869dd100-fc9f-11e9-8374-f6ebb3231ec0.png">

**Comment by MH-Zarkhani** [comment]
thank you
