### ISSUE TITLE
Group By function?

### ISSUE THREAD

**Issue by chrisvidal** [vojtasvoboda/oc-twigextensions-plugin#62]
Would be nice to have a `groupBy` function?

maybe form here https://github.com/dpolac/twig-lambda?

**Comment by vojtasvoboda** [comment]
Please send example code of how you would like to use it. GroupBy is part of the [Collections](https://octobercms.com/docs/services/collections) so you can easily use:

```
{% for item in items.groupBy('name').orderBy('name') %}
    ...
{% endfor %}
```

**Comment by chrisvidal** [comment]
I am trying to group my `products` by their `category`. Category is an object. not sure this would work

**Comment by vojtasvoboda** [comment]
When you preload categories (`$products = Product::with('categories')->all()`) then you should be able to group by category name like that: `$products->groupBy('categories.name')`, in template `{% for product in products.groupBy('categories.name') %}`.

**Comment by chrisvidal** [comment]
Hmmm not working

**Comment by vojtasvoboda** [comment]
So put your code in some public space and I will look at it. I'm a little bit blind without code :-)
