### ISSUE TITLE
Class 'Twig_Extensions_Extension_Text' not found with OctoberCMS v1.1.1

### ISSUE THREAD

**Issue by everyx** [vojtasvoboda/oc-twigextensions-plugin#63]
When install this plugin on OctoberCMS v1.1.1, I meet this error:

```shell
Class 'Twig_Extensions_Extension_Text' not found
/var/www/plugins/vojtasvoboda/twigextensions/Plugin.php line 152
```

**Comment by vojtasvoboda** [comment]
Try run `composer install` in the OctoberCMS root directory.

**Comment by everyx** [comment]
> Try run `composer install` in the OctoberCMS root directory.

@vojtasvoboda  I have run `composer install -a --quiet --no-dev --no-progress --ignore-platform-reqs` and I still get this error.

**Comment by vojtasvoboda** [comment]
So check if `/vendor/twig/extensions` directory exists. If yes, try `php artisan cache clear` and if using `php artisan serve` then stop it and start again.

**Comment by everyx** [comment]
> So check if `/vendor/twig/extensions` directory exists. If yes, try `php artisan cache clear` and if using `php artisan serve` then stop it and start again.

I can found the directory `plugins/vojtasvoboda/twigextensions/vendor/twig/extensions` is already exist, and I run `php artisan cache clear`, but this problem is still exist, maybe it's a bug of OcotberCMS v1.1.1?

**Comment by everyx** [comment]
I solved this problem, by 

```shell
# disable scripts
composer create-project --no-scripts october/october . 1.1.1;
# and run discover manually
php artisan package:discover;
```
