### ISSUE TITLE
Plugin prevents password retrieval

### ISSUE THREAD

**Issue by SplicedWeb** [vojtasvoboda/oc-twigextensions-plugin#64]
I discovered this plugin was the cause of not being able to reset a password [issue](https://octobercms.com/forum/post/password-reset-error).

Once disabled, along with any other plugins that rely on this plugin as a dependancy, I was able to retrieve a forgotten admin password.

**Comment by vojtasvoboda** [comment]
Hi @SplicedWeb thanks for your feedbeck. I just installed October v471 with this plugin and it seems to works:

<img width="584" alt="Snímek obrazovky 2021-01-14 v 20 57 10" src="https://user-images.githubusercontent.com/374917/104642420-2a0fb180-56ab-11eb-9315-500a2d2eb4ac.png">

Could you please provide step-by-step list how to reproduce this issue? October CMS version? Laravel 6? PHP version?

I would like to fix that, but I'm not able to reproduce it.

Thanks.
