### ISSUE TITLE
mode-js.js for October plugin - Twig Extensions (I think)

### ISSUE THREAD

**Issue by artisticdigital** [vojtasvoboda/oc-twigextensions-plugin#65]
I have Twig Extensions installed / updated. I'm getting a log error 404 for /modules/backend/formwidgets/codeeditor/assets/vendor/ace/mode-js.js    and I'm thinking this is part of the Twig Extension set.
The media interface is acting weird - not completing uploads. Sorry if this has nothing to do with Twig Extensions but if anyone has this file - I could use it.

**Comment by vojtasvoboda** [comment]
Path /modules/backend is part of the October's Backend module. It is not path within Twig plugin directory.
