### ISSUE TITLE
"Target class [twig.environment] does not exist" while running phpunit

### ISSUE THREAD

**Issue by vdomah** [vojtasvoboda/oc-twigextensions-plugin#66]
Hello!

Got a problem with this plugin while running phpunit. The following error occurs:

> An exception has been thrown during the compilation of a template ("Target class [twig.environment] does not exist.")

This line is causing it: https://github.com/vojtasvoboda/oc-twigextensions-plugin/blob/master/Plugin.php#L71

**Comment by vojtasvoboda** [comment]
Hello :-) Which version of October? Laravel 5/6? Trying to run `phpunit` on the whole project, or just on this plugin?

When trying October v 1.1.5 on Laravel 6:

<img width="651" alt="Screenshot 2021-07-27 v 23 56 32" src="https://user-images.githubusercontent.com/374917/127233229-8dcf33bb-3bf4-404f-bc11-f8ff2b1cad61.png">
