### ISSUE TITLE
Class "Twig_Extension_StringLoader" not found

### ISSUE THREAD

**Issue by wallichinz** [vojtasvoboda/oc-twigextensions-plugin#67]
basically the title says all. I went through all the folder structures but I don't know where the missing class should be. Has anyone else had this problem and knows how to fix this?

**Comment by markandmedia** [comment]
We are getting the same error, but only in a test project running octoberCMS V3

**Comment by wallichinz** [comment]
Thank you for your answer. I am currently downgrading again to 2.* and trying to avoid automatically installing the 3.*. 
I think the issue is on the new Laravel / Symphony Twig support.

**Comment by TimFoerster** [comment]
This is because ocms3 uses twig v3, instead of v1/2 instead and there whole extension system was changed.

**Comment by wallichinz** [comment]
@TimFoerster yes you are right I downgraded to 2.2 and it works perfectly.

**Comment by vojtasvoboda** [comment]
Any tips on how to solve this? Create a new plugin just for v3? Create legacy Git branch only for v1/v2?

**Comment by wallichinz** [comment]
@vojtasvoboda I think the main problem was the String or Array Extension as they are sometimes (as I've read) not loaded by default or have other names now. I tried to manually define some "old" methods directly where some errors "not defined etc." occurred and it worked in the 3.x. But it was to exhausting to find all twig changes and badly put them in the file where they were needed so I downgraded oct. CMS.

**Comment by TimFoerster** [comment]
@vojtasvoboda releasing it as v2 should be fine.
But IMHO ocms should provide all default available filters by twig https://twig.symfony.com/doc/3.x/filters/index.html 
which makes this plugin for most developers obsolete.  
Maybe you should start an discussion with Sam about it. You can also take a look `modules/cms/twig/Extension.php` to see how they implemented them.

**Comment by artisticdigital** [comment]
I posed this to OCMS help and got the following response:
"Generally, the Twig classes have been renamed to use namespaces. For example, a class can be namespace with the following conversion         **Twig_Extension_StringLoader → Twig\Extension\StringLoader**"
So at the very least it appears to be a naming issue. I'm going through and trying to adjust and will have a note into vojtasvoboda.

**Comment by vojtasvoboda** [comment]
I've tried changing all namespaces from Twig_Extension_* to Twig\Extension\*, but now it throws `Class "Twig_Extension" not found` on `plugins/vojtasvoboda/twigextensions/vendor/twig/extensions/lib/Twig/Extensions/Extension/Text.php`. There is a problem with Twig v2 vs Twig v3 as @TimFoerster mentioned.

So I set compatibility with Twig plugin just for October v1 and v2. October v3 stays untested for now.

**Comment by TimFoerster** [comment]
ocms 2/3 recevied some new twig methods/function with a new Carbon version. How about to abandoned this plugin for ocms3 and write a document with alternatives for each method? This should be less work compared to upgrading it to Twig 3.

For example mailto is implemented in ocms now:
`{{ a@b.c | mailto }}` => `<a href="mailto: {{ html_email('a@b.c')|raw }}">a@b.c</a>`

Or using Carbon 2
`{{ post.published_at | localizeddate('medium', 'none', locale) }}` => `post.published_at.locale(locale).isoFormat('L')`

**Comment by vojtasvoboda** [comment]
Yes sure, why not. Do you have a list of new functions we can use? I can update readme with that.

Anyway, there is a lot of filters we can use in October 3 and it would be fine to have October 3 100% compatible version.

**Comment by maki3000** [comment]
I actually would like to do a version of this plugin for OC v3.x. Or is already somebody else into it?

But with my limited PHP knowledge, I have some question. Maybe I would achieve it with some help.

So, I had a look at `modules/cms/twig/Extension.php` and thought, that like following it should work. I thought, I do just the uppercase filter as a start and later add all others, when I know, how to do it.

This is the boot method in Plugin.php:
```
public function boot()
    {
        // init Twig
        $twig = $this->app->make('twig.environment');
        // add new twig extensions
        $twig->addExtension(new OcTwigExtension());
}
```
Then I created a new class OcTwigExtension:
```
class OcTwigExtension extends TwigExtension
{
    /**
     * getFunctions returns a list of functions to add to the existing list.
     * @return array
     */
    public function getFunctions()
    {
        return [
            new TwigSimpleFunction('uppercase', [$this, 'uppercaseFunction'], ['is_safe' => ['html']]),
        ];
    }

    /**
     * uppercaseFunction converts text uppercase.
     * @return bool
     */
    public function uppercaseFunction($string)
    {
        return (string) mb_convert_case($string, MB_CASE_UPPER, "UTF-8");
    }
}
```
But the uppercase filter seems to be unknown like this.

**Comment by daftspunk** [comment]
Hello, most of this functionality is now included in the core. See issue #72 for details.

**Comment by vojtasvoboda** [comment]
Hello all (@mwahlmueller, @markandmedia, @TimFoerster, @artisticdigital, @maki3000), new version of the plugin is available on the market and is compatible with October 3.1 and PHP 8.0.

A lot of filters/functions were removed because they are part of the October CMS now. See [UPGRADE.MD](https://github.com/vojtasvoboda/oc-twigextensions-plugin/blob/master/UPGRADE.md) guide to learn more.

On the other hand, some new filters/functions were added: country_timezones, country_name, currency_name, currency_symbol, language_name, locale_name, timezone_name, format_currency, format_number and format_*_number, format_datetime, format_date and format_time - they are part of the official [twig/intl-extra](https://github.com/twigphp/intl-extra) package.
