### ISSUE TITLE
New version won't update

### ISSUE THREAD

**Issue by ndcisiv** [vojtasvoboda/oc-twigextensions-plugin#68]
I cannot install the new 1.3 version, either by updating the 1.2 or by a new installation.  OctoberCMS is completely up to date but here is what I get when I try to install this new version.

Problem 1
    - laravel/framework[v6.0.0, ..., 6.x-dev] require symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4, ..., 4.4.x-dev].
    - symfony/http-kernel[v4.3.4, ..., 4.4.x-dev] conflict with symfony/translation <4.2.
    - vojtasvoboda/twigextensions-plugin[1.3, ..., 1.x-dev] require symfony/translation ~3.3.9 -> satisfiable by symfony/translation[v3.3.9, ..., 3.3.x-dev].
    - Root composer.json requires vojtasvoboda/twigextensions-plugin ^1.3 -> satisfiable by vojtasvoboda/twigextensions-plugin[1.3, 1.x-dev].
    - Root composer.json requires laravel/framework ^6.0 -> satisfiable by laravel/framework[v6.0.0, ..., 6.x-dev].

**Comment by vojtasvoboda** [comment]
Which version of OctoberCMS and PHP, please?

**Comment by vojtasvoboda** [comment]
It works with old October v476 and PHP 7.4, but I removed composer.lock, which should help you install an older version.

**Comment by TimFoerster** [comment]
does not work with ocmsv2

`vojtasvoboda/twigextensions-plugin[1.2.0, ..., 1.2.7] require symfony/translation ~3.3.9 -> satisfiable by symfony/translation[v3.3.9, ..., 3.3.x-dev].`
=> `"symfony/translation": "~2.8|~3.0"`

`laravel/framework[v6.0.0, ..., 6.x-dev] require symfony/http-kernel ^4.3.4 -> found symfony/http-kernel[v4.3.4, ..., 4.4.x-dev]`
=> conflict: `"symfony/translation": "<4.2"`

https://github.com/symfony/http-kernel/blob/04181de9459df639512dadf83d544ce12edd6776/composer.json#L55

**Comment by Davox08** [comment]
I have the same problem when trying to install the plugin on version 2.2.27 of OctoberCMS

![Captura de pantalla 2022-05-30 184108](https://user-images.githubusercontent.com/42631079/171068531-515efeee-f38b-4fc1-ae01-9ce886455281.jpg)

**Comment by vojtasvoboda** [comment]
Please try it again with the new version 1.3.1. There was conflict with symfony/translation package using by symfony/http-kernel.

**Comment by Davox08** [comment]
In my case everything works correctly, I have been able to update it successfully. Thank you very much for your help.

**Comment by vojtasvoboda** [comment]
@TimFoerster @ndcisiv Could you please guys also test it? Thanks

**Comment by TimFoerster** [comment]
@vojtasvoboda 
`  - Upgrading vojtasvoboda/twigextensions-plugin (v1.2.7 => 1.3.1): Extracting archive`
success

**Comment by ndcisiv** [comment]
My apologies for the late response, I was way for the holiday weekend.
I am on OctoberCMS v2.2.27, PHP 7.4.2.
I can verify that after your modifications I am now 100% able to install it again.  Thank you very much.
