### ISSUE TITLE
Cannot install it with composer on latest version of OctoberCMS

### ISSUE THREAD

**Issue by cdarken** [vojtasvoboda/oc-twigextensions-plugin#7]
I'm trying to install you package using composer: `composer require vojtasvoboda/oc-twigextensions-plugin:dev-master`. But I get this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vojtasvoboda/oc-twigextensions-plugin dev-master -> satisfiable by vojtasvoboda/oc-twigextensions-plugin[dev-master].
    - Conclusion: remove symfony/translation v2.7.16
    - Conclusion: don't install symfony/translation v2.7.16
    - vojtasvoboda/oc-twigextensions-plugin dev-master requires symfony/translation ^3.0 -> satisfiable by symfony/translation[3.0.x-dev, 3.1.x-dev, 3.2.x-dev, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.2, v3.1.3].
    - Can only install one of: symfony/translation[3.0.x-dev, v2.7.16].
    - Can only install one of: symfony/translation[3.1.x-dev, v2.7.16].
    - Can only install one of: symfony/translation[3.2.x-dev, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.0, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.0-BETA1, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.1, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.2, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.3, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.4, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.5, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.6, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.7, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.8, v2.7.16].
    - Can only install one of: symfony/translation[v3.0.9, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.0, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.0-BETA1, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.0-RC1, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.1, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.2, v2.7.16].
    - Can only install one of: symfony/translation[v3.1.3, v2.7.16].
    - Installation request for symfony/translation (locked at v2.7.16) -> satisfiable by symfony/translation[v2.7.16].
```

This happens event if I install it from the admin panel and I do a `composer update`, because of the `wikimedia/composer-merge-plugin` added recently.
This seems to happen because of this dependency in laravel 5.1: "symfony/translation": "2.7.*".

Any advice on how to use your plugin with composer ?
Thanks!

**Comment by cdarken** [comment]
Update: got it to install by overriding the dependency version, adding this to require section:

```
"symfony/translation": "3.0.0 as 2.7.16"
```

**Comment by cdarken** [comment]
But it doesn't appear in the manage plugins page in backend.

**Comment by vojtasvoboda** [comment]
Try it now please

**Comment by cdarken** [comment]
The installation went ok, but the plugin is not detected, not in the interface and not when running `artisan october:up`. I will try to create a project from scratch and just install this plugin. I'll be back with news.

**Comment by cdarken** [comment]
Yup. The plugin is not detected.

**Comment by vojtasvoboda** [comment]
Hmm hmm, look like the composer install plugin to directory /plugins/vojtasvoboda/oc-twigextensions, but it should be /plugins/vojtasvoboda/twigextensions/

Don't you now if there is some composer parameter to override target directory name?

**Comment by cdarken** [comment]
Take a look here: https://github.com/composer/installers/blob/master/src/Composer/Installers/BaseInstaller.php
There seems to be a check for the key `installer-paths` at line 58. I don't find the documentation for it though.

Edit:
Sorry, here it is: http://composer.github.io/installers/
The "installer-name" option seems to be the winner here.

**Comment by cdarken** [comment]
Yes, I've forked your repo and forced install from my fork, it's working.

**Comment by vojtasvoboda** [comment]
Thanks a lot, I just updated composer.json, so you can use origin repository to have all new updates 👍
