### ISSUE TITLE
october 3.x

### ISSUE THREAD

**Issue by patosG** [vojtasvoboda/oc-twigextensions-plugin#70]
Hi. thanks for this plugin.
Any plan to make 3.x compatible ?

regards

**Comment by PubliAlex** [comment]
+1 here, when trying to install it on october 3, composer report many errors : 
![image](https://user-images.githubusercontent.com/55833027/187915755-4ccd6238-fd6b-4631-85d3-483063f58269.png)

**Comment by daftspunk** [comment]
Hello, most of this functionality is now included in the core. See issue #72 for details.

**Comment by vojtasvoboda** [comment]
Hello all (@patosG, @PubliAlex), a new version of the plugin is available on the market and is compatible with October 3.1 and PHP 8.0.
