### ISSUE TITLE
Struggling to update to latest version

### ISSUE THREAD

**Issue by Loop-Paul** [vojtasvoboda/oc-twigextensions-plugin#71]
Morning Vojta,

Just a message to see if you can shed some light on an issue we are currently having.

We are trying to update the extension through SSH but for some reason it is not updating when we try. Can you provide any light into why this maybe happening or any steps we need to take so we can update to the latest version. We are currently on version 1.2.7.

Regards and thanks for your time.

**Comment by vojtasvoboda** [comment]
Hello @Loop-Paul, could you tell me which version of October CMS you are using, which PHP version and some errors you get?

Between version 1.2.7 and 1.3/1.3.1, there are no functional changes, only updates to make it works with October 2.x and PHP 8.

**Comment by Loop-Paul** [comment]
Afternoon Vojta,

Thanks for getting back to me and please see my notes below in relationship to your questions

- The version of October CMS is v2.2.34
- PHP version is 7.3.33
- In terms of errors, we didnt get any come up, it literally just doesnt update.

Regards and look forward to hearing from you

**Comment by vojtasvoboda** [comment]
Could you please try to find something in CMS backend > Settings > Event log, or in /storage/logs/system.log file? At least something we can stick with :-)

**Comment by Loop-Paul** [comment]
The only thing I could find was examples like this

Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 33554432 bytes exhausted (tried to allocate 327680 bytes) in ......../twig/src/Template.php:399

**Comment by vojtasvoboda** [comment]
Hello @Loop-Paul 

I just tried to install October 2.2.34 on PHP 7.3.33 with latest Twig Extension and it works:

<img width="711" alt="Screenshot 2022-10-29 v 21 49 36" src="https://user-images.githubusercontent.com/374917/198850205-dab7d34b-eb3e-4d04-9db5-de8b97f43fe9.png">

Below is composer.json I've used:

```
{
    "require": {
        "php": ">=7.2.9",
        "october/rain": "^2.0",
        "laravel/framework": "^6.0",
        "october/system": "^2.0",
        "october/backend": "^2.0",
        "october/cms": "^2.0",
        "october/media": "^2.0",
        "october/editor": "^2.0",
        "vojtasvoboda/oc-twigextensions-plugin": "1.3.1"
    },
}
```
To be honest, I wasn't able to install Twig Extension 1.2.7, because there were some dependency problems. So just try to include exactly version 1.3.1, run `composer install` and on the end don't forget to run:

`php artisan october:migrate`

**Comment by vojtasvoboda** [comment]
One more thing, in the error message you sent me, there is something about 32 MB of memory - from my point of view, it's not much. Maybe try to increase the memory limit for PHP by at least to 128 MB.

I close this issue for now, but I will reopen it, if you will need more help.

**Comment by Loop-Paul** [comment]
Morning Vojta,

Thanks for getting back to me with your replies and I will look to use this info to see if we can get to the bottom of our issue, many thanks
