### ISSUE TITLE
Incompatible with October v3.0

### ISSUE THREAD

**Issue by prhost** [vojtasvoboda/oc-twigextensions-plugin#73]
Hello, would it be possible to reduce the version of `october/rain` to support version 3.0? Is there something you only use in v3.1 and don't have in v3.0?

![Screenshot 2022-11-23 at 14 02 40](https://user-images.githubusercontent.com/3984760/203606337-0fd2cc3d-098e-46a1-ab13-407950cf22c1.png)

![Screenshot 2022-11-23 at 14 04 15](https://user-images.githubusercontent.com/3984760/203606657-7638c02d-bfe7-4af4-b4c5-41e3da2ae7b7.png)

**Comment by vojtasvoboda** [comment]
Hello @prhost, I just set 3.0, could you please try it again? Thanks

**Comment by prhost** [comment]
> Hello @prhost, I just set 3.0, could you please try it again? Thanks

For some reason it didn't update the packagist https://packagist.org/packages/vojtasvoboda/oc-twigextensions-plugin#dev-master

**Comment by vojtasvoboda** [comment]
Ok, so I tag the new version 2.0.2. The package is auto-updated so now we have to wait for Packagist. Please let me know.

**Comment by vojtasvoboda** [comment]
@prhost Version 2.0.2 is ready on Packagist.
