### ISSUE TITLE
Class "IntlDateFormatter" not found

### ISSUE THREAD

**Issue by maki3000** [vojtasvoboda/oc-twigextensions-plugin#74]
Hello,

I just installed oc-twigextensions-plugin on a OC v3.1.26 and I'm getting:
`Class "IntlDateFormatter" not found`

I'm using the official OC docker image.

I tried to adjust the php.ini files in the attached docker shell, clearing the comment of:
`extension=intl`
Then I restarted my container with no luck.

How can I fix this?

**Comment by vojtasvoboda** [comment]
Hello @maki3000, which version of the plugin are you using? Could you try to look at the /plugins/vojtasvoboda/twigextensions/updates/version.yaml which version is on the last line?

**Comment by vojtasvoboda** [comment]
Version 2.0.2 looks good on my end.

<img width="854" alt="Screenshot 2022-11-30 v 9 24 21" src="https://user-images.githubusercontent.com/374917/204745459-3699c073-b56e-47a6-8096-db5006eb5b7e.png">

**Comment by maki3000** [comment]
Last line of /plugins/vojtasvoboda/twigextensions/updates/version.yaml is:
`2.0.2: Fix compatibility with October 3.0`

My backend also looks good. The error is appearing on my frontend, while I did not implement anything belonging to the plugin yet.

**Comment by vojtasvoboda** [comment]
Ok, so could you please send me a screenshot of the plugins list you have? I try to reproduce your environment.

I tried also frontend, using `ltrim` filter and all works well. It looks like some problem with Twig generally, because there is no `IntlDateFormatter` in my plugin.

**Comment by maki3000** [comment]
Here's my plugin-list (I needed to hide own plugins and name):
![oc-plugin-list](https://user-images.githubusercontent.com/1168196/204756995-08bf7cab-19b1-4c64-902d-6e66b2651e39.png)

And here's the stack trace, maybe that helps:
![oc-stacktrace-error](https://user-images.githubusercontent.com/1168196/204757176-d2721170-141e-4436-bc6f-e20d148e538e.png)

**Comment by vojtasvoboda** [comment]
Ok, so I made a fix, could you please try 2.0.3 version? It is ready on Packagist right now.

**Comment by maki3000** [comment]
Perfect! Thank you so much! I'm glad!

**Comment by vojtasvoboda** [comment]
@maki3000 I would be glad if you leave some comment on my plugin's page: https://octobercms.com/plugin/vojtasvoboda-twigextensions

:-)

**Comment by maki3000** [comment]
Ah! Yeah, sorry. The one that got the thanks can be glad 😅 🤦‍♂️

Just left a comment…

Thanks again and have a very nice day!
Maki
