### ISSUE TITLE
Error with format_datetime()

### ISSUE THREAD

**Issue by anestism** [vojtasvoboda/oc-twigextensions-plugin#75]
Hello,
I have been trying now for several hours but couldn't make it work: 
{{ '2019-08-07 23:39:12'|format_datetime('none', 'short', locale='fr') }} gives following error:
Unknown arguments "0", "1", "locale" for filter "format_datetime()".

{{ '2019-08-07 23:39:12'|format_datetime('none', 'short') } } gives:
Twig\Extra\Intl\IntlExtension::formatDateTime(): Argument #1 ($env) must be of type Twig\Environment, October\Rain\Argon\Argon given, called in /srv/vservers/www/stampit.gr/modules/system/classes/MarkupExtensionItem.php on line 166

I have tried on OctoberCMS 3.2.9 and 3.2.10
I have tried installing your plugin the "traditional way" with php artisan plugin:install  
and with
composer require vojtasvoboda/oc-twigextensions-plugin
php artisan plugin:install VojtaSvoboda.TwigExtensions
on different websites

Any idea what is missing?
Some other functions work fine. I think just those which are related to a locale have a problem. (Locale is set and I confirmed it by displaying it on the page)

**Comment by vojtasvoboda** [comment]
Yes, you're right, three filters require an environment: https://github.com/twigphp/intl-extra/blob/2.x/IntlExtension.php#L144 to be somehow injected into the filter.

I tried to solve it in 15 minutes, but without any output for now :-(

**Comment by chocolata** [comment]
Hi, I'm encountering the same issues and the exact same error messages. Our service provider says that the phpIntl extension is installed for my version of PHP. 

Do you maybe know of a workaround?

**Comment by vojtasvoboda** [comment]
As I said above, the problem is passing Twig\Environment to these filters. So there is no problem with phpIntl installed on hosting/server.

The issue is still open, feel free to send a pull request with the fix.

**Comment by chocolata** [comment]
Hi @vojtasvoboda - thanks for clarifying, I didn't understand fully. I'm afraid that this is a bit above my level of expertise... I hope that maybe someone else is knowledgeable enough to provide a pull request...

**Comment by chrisvidal** [comment]
stumble on the same error...
I see that the plugin OFFLINE.Mall is succeeding to inject the twig env when it uses the currency formation function for the IntlExtension, but I cant make it work with this plugin. 

Maybe that gives you a hint to fix this.

in the plugin.php, I tried this as per the Twig Format_date documentation https://twig.symfony.com/doc/3.x/filters/format_date.html

```php
function register() {
        $this->twig = new Environment(new TwigLoader, ['auto_reload' => true]);
        $this->twig->addExtension(new IntlExtension());
}
```

and then adding the filter like this

```php
$filters += [
                'format_date' => function ($date, ?string $dateFormat = 'medium', string $pattern = '', $timezone = null, string $calendar = 'gregorian', string $locale = null) use ($twig): string {
                    $intlExtension = new IntlExtension();
                    return $intlExtension->formatDate($twig, $date,  $dateFormat,  $pattern, $timezone,  $calendar,  $locale);
                }
            ];
```

**Comment by vojtasvoboda** [comment]
@chrisvidal Thanks for the hint about adding an extension directly to the Twig. It works brilliant :-) The new version is ready in the Market as version 2.0.4 🥳

@chocolata Please test, thanks.

**Comment by chocolata** [comment]
Hi @vojtasvoboda 

Just tested this out and it works perfectly. In my usecase I managed to output the localized month name of my application like this:

`{{ '2024-06-01' | format_date('none','MMMM',locale=this.site.locale) }}`

Thanks for your work! Much appreciated.

**Comment by chrisvidal** [comment]
excellent! thanks

however, when I install the plugin on a new installation, I have this error `[2024-05-12 17:26:31] production.ERROR: Error: Class "IntlDateFormatter" not found in /var/www/valhiraoka.com/public_html/plugins/vojtasvoboda/twigextensions/Plugin.php:36`

I tried to `composer update` but it does not change anything.

**Comment by vojtasvoboda** [comment]
@chrisvidal Thanks for testing. The fixed version is ready for download :-) Please test it again and let me know.
