### ISSUE TITLE
Unknown "truncate" filter.

### ISSUE THREAD

**Issue by xinix** [vojtasvoboda/oc-twigextensions-plugin#76]
I installed the plugin on my local October 3 installation. I cant call this function...

If I remove the truncate filter, I get this error:

`twig_template_from_string(): Argument #1 ($env) must be of type Twig\Environment, string given, called in /var/www/html/modules/system/classes/MarkupExtensionItem.php on line 166`

**Comment by vojtasvoboda** [comment]
Could you please send me a code snippet of how you use it?

**Comment by xinix** [comment]
```
{{ post.featured_text|truncate(50) }}
```

**Comment by vojtasvoboda** [comment]
Truncate is not available for October v3, only for v2/v1. For October v3 use official `str_limit` function:

(https://docs.octobercms.com/3.x/markup/function/str.html#str-limit)
