### ISSUE TITLE
Conflicting dependency with Laravel 5.1

### ISSUE THREAD

**Issue by nathan-van-der-werf** [vojtasvoboda/oc-twigextensions-plugin#9]
When installing this plugin in the newest version of OctoberCMS (with Laravel 5.1) you'll get a conflict on the Symonfy/Translation dependency.

Your plugin requires "symfony/translation": "^3.0" while Laravel 5.1 requires "symfony/translation": "2.7.*"

**Comment by vojtasvoboda** [comment]
Try it now please, I have updated dependencies to be compatible with Laravel 5.1 requirements.

**Comment by nathan-van-der-werf** [comment]
It worked.
